#pragma once

#define FIRMWARE_PRODUCT_NAME "TransitInk OS"
#define FIRMWARE_SHORT_NAME "TransitInk"
#define FIRMWARE_PRODUCT_ID "transitink-os"
#define FIRMWARE_BOARD_ID "zectrix_note4"
#define DEVICE_NAME FIRMWARE_PRODUCT_NAME
#define FIRMWARE_VERSION "1.1.1"
#define CONFIG_AP_PREFIX FIRMWARE_SHORT_NAME

#ifndef TRANSITINK_FIRMWARE_UPDATE_BASE_URL
#define TRANSITINK_FIRMWARE_UPDATE_BASE_URL \
    "https://zerie55699.github.io/transitink-os"
#endif

#define ETA_REFRESH_DEFAULT_SECONDS 45
#define ETA_MAX_ROUTES 4
#define WIDGET_PAGE_CACHE_TTL_SECONDS 180
#define WEATHER_REFRESH_SECONDS 900
#define SLEEP_ENABLED_DEFAULT 1
#define SLEEP_WAKE_DEFAULT_MINUTES 5
#define SLEEP_MAINTENANCE_DEFAULT_HOURS 12
#define SCHEDULED_WAKE_ENABLED_DEFAULT 0
#define SCHEDULED_WAKE_START_DEFAULT_MINUTES 480
#define SCHEDULED_WAKE_END_DEFAULT_MINUTES 540
