#pragma once

#define FIRMWARE_PRODUCT_NAME "TransitInk OS"
#define FIRMWARE_SHORT_NAME "TransitInk"
#define DEVICE_NAME FIRMWARE_PRODUCT_NAME
#define FIRMWARE_VERSION "1.0.0"
#define CONFIG_AP_PREFIX FIRMWARE_SHORT_NAME
#define CONFIG_AP_PASSWORD ""

#define ETA_REFRESH_DEFAULT_SECONDS 45
#define ETA_MAX_ROUTES 4
#define WEATHER_REFRESH_SECONDS 900
#define SLEEP_ENABLED_DEFAULT 1
#define SLEEP_WAKE_DEFAULT_MINUTES 5
#define SLEEP_MAINTENANCE_DEFAULT_HOURS 12
